name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/target/*.jar"
          target: "~/psa-web-krawler/"
          strip_components: 2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop existing app (if running)
            pkill -f 'java -jar' || echo "No app running"
            sleep 5  # Give the old process time to stop

            # Rename the uploaded jar to app.jar
            mv ~/psa-web-krawler/*.jar ~/psa-web-krawler/app.jar

            # Create a startup script
            cat << 'EOF' > ~/psa-web-krawler/start.sh
            #!/bin/bash
            cd ~/psa-web-krawler
            nohup java -jar app.jar \
              --spring.neo4j.uri=${{ secrets.NEO4J_BOLT_URL }} \
              --spring.neo4j.authentication.username=${{ secrets.NEO4J_USERNAME }} \
              --spring.neo4j.authentication.password=${{ secrets.NEO4J_PASSWORD }} \
              > app.log 2>&1 &

            # Wait a few seconds to check if the process is still running
            sleep 10
            if pgrep -f 'java -jar.*app.jar' > /dev/null; then
              echo "Application started successfully"
              exit 0
            else
              echo "Application failed to start. Last 50 lines of log:"
              tail -n 50 app.log
              exit 1
            fi
            EOF

            # Make the script executable
            chmod +x ~/psa-web-krawler/start.sh

            # Run the startup script
            ~/psa-web-krawler/start.sh
