name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/target/*.jar"
          target: "~/psa-web-krawler/"
          strip_components: 2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            # Debug uploaded files
            ls -l ~/psa-web-krawler/

            # Stop existing app (if running)
            pkill -f 'java -jar' || echo "No app running"
            sleep 5

            # Rename the uploaded jar to app.jar
            mv ~/psa-web-krawler/*.jar ~/psa-web-krawler/app.jar

            # Ensure proper permissions
            sudo chown ${{ secrets.EC2_USER }}:$${{ secrets.EC2_USER }} ~/psa-web-krawler/app.jar

            # Create systemd service file
            sudo tee /etc/systemd/system/webkrawler.service > /dev/null << EOF
            [Unit]
            Description=Web Krawler Spring Boot Application
            After=network.target

            [Service]
            Type=simple
            User=${{ secrets.EC2_USER }}
            WorkingDirectory=/home/${{ secrets.EC2_USER }}/psa-web-krawler
            ExecStart=/usr/bin/java -jar app.jar \
              --spring.neo4j.uri=${{ secrets.NEO4J_BOLT_URL }} \
              --spring.neo4j.authentication.username=${{ secrets.NEO4J_USERNAME }} \
              --spring.neo4j.authentication.password=${{ secrets.NEO4J_PASSWORD }}
            SuccessExitStatus=143
            TimeoutStopSec=10
            Restart=always
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
            EOF

            # Reload and restart systemd service
            sudo systemctl daemon-reload
            sudo systemctl restart webkrawler

            # Check service status
            sleep 10
            sudo systemctl is-active --quiet webkrawler && sudo systemctl status webkrawler || {
              echo "Service failed to start. Logs:"
              sudo journalctl -u webkrawler -n 50 --no-pager
              exit 1
            }
