name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # Step 3: Build the Spring Boot app
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop existing app (if running)
            pkill -f 'java -jar' || echo "No app running"

            # Upload the JAR file
            scp target/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/psa-web-krawler/app.jar

            # Start the app
            nohup java -jar ~/psa-web-krawler/app.jar --spring.neo4j.uri=${{ secrets.NEO4J_BOLT_URL }} --spring.neo4j.authentication.username=${{ secrets.NEO4J_USERNAME }} --spring.neo4j.authentication.password=${{ secrets.NEO4J_PASSWORD }} &
