name: Deploy Spring Boot App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build with Maven
        run: |
          cd backend
          mvn clean package

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/target/*.jar"
          target: "~/psa-web-krawler/"
          strip_components: 2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop existing app (if running)
            pkill -f 'java -jar' || echo "No app running"

            # Rename the uploaded jar to app.jar
            mv ~/psa-web-krawler/*.jar ~/psa-web-krawler/app.jar

            # Start the app
            nohup java -jar ~/psa-web-krawler/app.jar \
              --spring.neo4j.uri=${{ secrets.NEO4J_BOLT_URL }} \
              --spring.neo4j.authentication.username=${{ secrets.NEO4J_USERNAME }} \
              --spring.neo4j.authentication.password=${{ secrets.NEO4J_PASSWORD }} > ~/psa-web-krawler/app.log 2>&1 &
